unique_ids:
  assets:
    standard-page.html: MPERLRYBZOPTHXQ4UNN4VHAAPF3GOSSF
    theme.css: Y5AWRSLISJPUOWRP65SREN3NQTSWQ5ZH
  forms:
    Form1: NRHWHQAMQGWBOALGDFJ7APFHCL5AVFIK
  modules: {}
  scripts: {}
  server_modules: {}
